---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "vollmed-pacientes-secrets"
  labels:
    app.kubernetes.io/name: "vollmed-apphost"
    app.kubernetes.io/component: "vollmed-pacientes"
    app.kubernetes.io/instance: "{{.Release.Name}}"
stringData:
  ConnectionStrings__pacientesDB: "Server=sqlserver-service,1433;User ID=sa;Password={{ .Values.secrets.vollmed_pacientes.sqlserver_password }};TrustServerCertificate=true;Initial Catalog=pacientesDB"
  PACIENTESDB_PASSWORD: "{{ .Values.secrets.vollmed_pacientes.sqlserver_password }}"
  ConnectionStrings__rabbitmq: "amqp://guest:{{ .Values.secrets.vollmed_pacientes.rabbitmq_password }}@rabbitmq-service:5672"
  RABBITMQ_PASSWORD: "{{ .Values.secrets.vollmed_pacientes.rabbitmq_password }}"
  RABBITMQ_URI: "amqp://guest:{{ .Values.secrets.vollmed_pacientes.rabbitmq_password }}@rabbitmq-service:5672"
type: "Opaque"
