---
apiVersion: "apps/v1"
kind: "StatefulSet"
metadata:
  name: "postgres-statefulset"
  labels:
    app.kubernetes.io/name: "vollmed-apphost"
    app.kubernetes.io/component: "postgres"
    app.kubernetes.io/instance: "{{.Release.Name}}"
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "vollmed-apphost"
        app.kubernetes.io/component: "postgres"
        app.kubernetes.io/instance: "{{.Release.Name}}"
    spec:
      containers:
        - image: "docker.io/library/postgres:15"
          name: "postgres"
          envFrom:
            - configMapRef:
                name: "postgres-config"
          ports:
            - name: "tcp"
              protocol: "TCP"
              containerPort: 5432
          volumeMounts:
            - name: "keycloak-pgdata"
              mountPath: "/var/lib/postgresql/data"
          imagePullPolicy: "IfNotPresent"
      volumes:
        - name: "keycloak-pgdata"
          emptyDir: {}
  selector:
    matchLabels:
      app.kubernetes.io/name: "vollmed-apphost"
      app.kubernetes.io/component: "postgres"
      app.kubernetes.io/instance: "{{.Release.Name}}"
  replicas: 1
  persistentVolumeClaimRetentionPolicy: {}
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 0
    type: "RollingUpdate"
