---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "sqlserver-secrets"
  labels:
    app.kubernetes.io/name: "vollmed-apphost"
    app.kubernetes.io/component: "sqlserver"
    app.kubernetes.io/instance: "{{.Release.Name}}"
stringData:
  MSSQL_SA_PASSWORD: "{{ .Values.secrets.sqlserver.sqlserver_password }}"
type: "Opaque"
